"""init all models

Revision ID: 3d622ee820f5
Revises: 
Create Date: 2025-11-28 23:01:29.415420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d622ee820f5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=True),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('colore_code', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tb_category_id'), 'tb_category', ['id'], unique=False)
    op.create_table('tb_invitation_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_1', sa.String(length=250), nullable=True),
    sa.Column('name_2', sa.String(length=250), nullable=True),
    sa.Column('date_1', sa.Date(), nullable=True),
    sa.Column('date_2', sa.Date(), nullable=True),
    sa.Column('is_template_need', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tb_invitation_profile_id'), 'tb_invitation_profile', ['id'], unique=False)
    op.create_table('tb_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tb_users_id'), 'tb_users', ['id'], unique=False)
    op.create_table('tb_invitation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('event_title', sa.String(length=250), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('event_time', sa.Time(), nullable=True),
    sa.Column('venue_name', sa.String(length=250), nullable=True),
    sa.Column('venue_address', sa.String(length=250), nullable=True),
    sa.Column('note', sa.String(length=250), nullable=True),
    sa.Column('event_photo', sa.String(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['tb_users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_type'], ['tb_category.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tb_invitation_id'), 'tb_invitation', ['id'], unique=False)
    op.create_table('tb_sub_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=10), nullable=True),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('colore_code', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['tb_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tb_sub_category_id'), 'tb_sub_category', ['id'], unique=False)
    op.create_table('tb_invitation_guests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invitation', sa.Integer(), nullable=True),
    sa.Column('guest', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['guest'], ['tb_users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invitation'], ['tb_invitation.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tb_invitation_guests_id'), 'tb_invitation_guests', ['id'], unique=False)
    op.create_table('tb_sub_invitation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('event_title', sa.String(length=250), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('event_time', sa.Time(), nullable=True),
    sa.Column('venue_name', sa.String(length=250), nullable=True),
    sa.Column('venue_address', sa.String(length=250), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('event_photo', sa.String(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['tb_users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_type'], ['tb_sub_category.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tb_sub_invitation_id'), 'tb_sub_invitation', ['id'], unique=False)
    op.create_table('tb_sub_invitation_guests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sub_invitation', sa.Integer(), nullable=True),
    sa.Column('guest', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['guest'], ['tb_users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sub_invitation'], ['tb_sub_invitation.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tb_sub_invitation_guests_id'), 'tb_sub_invitation_guests', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tb_sub_invitation_guests_id'), table_name='tb_sub_invitation_guests')
    op.drop_table('tb_sub_invitation_guests')
    op.drop_index(op.f('ix_tb_sub_invitation_id'), table_name='tb_sub_invitation')
    op.drop_table('tb_sub_invitation')
    op.drop_index(op.f('ix_tb_invitation_guests_id'), table_name='tb_invitation_guests')
    op.drop_table('tb_invitation_guests')
    op.drop_index(op.f('ix_tb_sub_category_id'), table_name='tb_sub_category')
    op.drop_table('tb_sub_category')
    op.drop_index(op.f('ix_tb_invitation_id'), table_name='tb_invitation')
    op.drop_table('tb_invitation')
    op.drop_index(op.f('ix_tb_users_id'), table_name='tb_users')
    op.drop_table('tb_users')
    op.drop_index(op.f('ix_tb_invitation_profile_id'), table_name='tb_invitation_profile')
    op.drop_table('tb_invitation_profile')
    op.drop_index(op.f('ix_tb_category_id'), table_name='tb_category')
    op.drop_table('tb_category')
    # ### end Alembic commands ###
