
services:
  user_db:
    image: postgres:16
    container_name: wedding_db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_HOST_PORT:-6000}:5432"
    volumes:
      - wedding_db_data:/var/lib/postgresql/data

  mongodb:
    image: mongo:7.0
    container_name: invitation_mongodb
    env_file:
      - .env
    environment:
      MONGO_INITDB_DATABASE: ${MONGODB_NAME:-invitation_chat_db}
    ports:
      - "${MONGODB_HOST_PORT:-27017}:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  wedding_db_data:
  mongodb_data: